# Generated by Django 4.1.1 on 2022-09-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number'),
        ),
    ]
