# Generated by Django 4.1.1 on 2022-09-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='wallet',
            field=models.FloatField(default=0, null=True, verbose_name='Wallet'),
        ),
    ]
