# Generated by Django 4.1.1 on 2022-09-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_alter_customer_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Company Name')),
                ('digitprefix', models.IntegerField(null=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': ' Company ',
            },
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('planName', models.CharField(max_length=100, null=True, verbose_name='Plan Name')),
                ('price', models.FloatField(default=0, null=True, verbose_name='Price')),
                ('duration', models.CharField(max_length=50, null=True, verbose_name='Duration')),
            ],
            options={
                'verbose_name_plural': ' Plans ',
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='Phone Number')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='company.company', verbose_name=' Company Name')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='accounts.customer', verbose_name='Customer')),
            ],
            options={
                'verbose_name_plural': 'Subscription',
            },
        ),
    ]
