# Generated by Django 4.1.1 on 2022-09-21 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customer_wallet'),
        ('company', '0002_alter_company_digitprefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Customer Name')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.plans', verbose_name='Plan Name')),
                ('registered_sim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companysubscription', verbose_name='Customer Registered Sim')),
            ],
            options={
                'verbose_name_plural': 'Plan Subscription',
            },
        ),
        migrations.AddIndex(
            model_name='plansubscription',
            index=models.Index(fields=['id', 'plan', 'customer'], name='company_pla_id_32adac_idx'),
        ),
    ]
