# Generated by Django 4.1.1 on 2022-09-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_plansubscription_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name_plural': 'Sim Subscription'},
        ),
        migrations.AddIndex(
            model_name='companysubscription',
            index=models.Index(fields=['id', 'company', 'customer'], name='company_com_id_4abbeb_idx'),
        ),
    ]
