# Generated by Django 3.2.6 on 2022-09-22 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customer_wallet'),
        ('company', '0004_alter_companysubscription_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('phoneNumber', models.CharField(max_length=11, null=True, verbose_name='Phone Number')),
                ('offerName', models.CharField(max_length=100, null=True, verbose_name='Offer Name')),
                ('offerPrice', models.FloatField(default=0, null=True)),
                ('offerDuration', models.CharField(max_length=100, null=True, verbose_name='Offer Duration')),
                ('status', models.CharField(choices=[('1', 'Activate'), ('2', 'Cancel')], max_length=15, null=True, verbose_name='Offer Status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.customer', verbose_name='Customer Name')),
            ],
            options={
                'verbose_name_plural': 'Customer Offer Tracking',
            },
        ),
        migrations.AddIndex(
            model_name='trackingcustomer',
            index=models.Index(fields=['id', 'customer'], name='company_tra_id_116bf1_idx'),
        ),
    ]
